spring.datasource.url=jdbc:postgresql://localhost:5432/reservas_alura_DB
spring.datasource.username=postgres
spring.datasource.password=iggor051

# Hibernate cria/atualiza tabelas automaticamente.
spring.jpa.hibernate.ddl-auto=update

# Mostra SQL no console.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Informa ao Hibernate qual banco está sendo usado.
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect